#!/bin/bash

case $1 in
    suspend)
        swaylock --clock \
            --indicator \
            --screenshots \
            --effect-scale 0.4 \
            --effect-vignette 0.2:0.5 \
            --effect-blur 4x2 \
            --datestr '%a %e.%m.%Y' \
            --timestr '%k:%M' && sleep 3 && systemctl suspend
        ;;

    *)
        swaylock --clock \
            --indicator \
            --screenshots \
            --effect-scale 0.4 \
            --effect-vignette 0.2:0.5 \
            --effect-blur 4x2 \
            --datestr '%a %e.%m.%Y' \
            --timestr '%k:%M'
        ;;
esac
